name: khazana_task
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_svg: ^2.0.17
  gap: ^3.0.1
  pinput: ^5.0.1
  stop_watch_timer: ^3.2.1
  supabase_flutter: ^2.8.4
  get_storage: ^2.1.1
  fl_chart:
  intl: ^0.20.2
  syncfusion_flutter_charts: ^29.1.33
  flutter_sliding_toast: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/


